version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bidichk
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    revive:
      enable-all-rules: false
      rules:
        - name: receiver-naming
          severity: warning
          disabled: false
          exclude:
            - ""
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - cmd/test
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - cmd/test
      - third_party$
      - builtin$
      - examples$
